version: "3"
services:
  nginx:
    image: nginx:latest
    stdin_open: true
    tty: true
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: '.docker/'
    volumes:
      - './:/var/www'